export enum CategoryAllowFields {
  id = 'id',
  known = 'known',
  name = 'name',
  products = 'products',
  sameAs = 'sameAs',
  url = 'url',
}

export enum ProductAllowFields {
  _id = '_id',
  _keywords = '_keywords',
  product_name = 'product_name',
  brands = 'brands',
  categories = 'categories',
  "lang"="lang",
  allergens_tags = 'allergens_tags',
  categories_tags = 'categories_tags',
  allergens_from_ingredients = 'allergens_from_ingredients',
  allergens_from_user = 'allergens_from_user',
  nutriscore_grade = 'nutriscore_grade',
  nutriscore_score = 'nutriscore_score',
  nova_group = 'nova_group',
  nutriments = 'nutriments',
  ingredients_text = 'ingredients_text',
  ingredients_tags = 'ingredients_tags',
  additives_tags = 'additives_tags',
  vitamins_tags = 'vitamins_tags',
  minerals_tags = 'minerals_tags',
  labels_tags = 'labels_tags',
  image_url = 'image_url',
  image_small_url = 'image_small_url',
  image_front_url = 'image_front_url',
  image_front_small_url = 'image_front_small_url',
  image_ingredients_url = 'image_ingredients_url',
  image_nutrition_url = 'image_nutrition_url',
  code = 'code',
}
